# baseURL = "https://rahulguha.github.io/rahul-guha-public/"
baseURL = "https://rahul-guha.com"
languageCode = "en"
DefaultContentLanguage = "en"


theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
customCss = ["css/styles.css"]

[params]
author = "Rahul Guha"
title = "Rahul Guha's Homepage "
description = '''
Call me Rahul
This is multiline description
'''
mainSections = ["tech", "post"]
profilePicture = "images/profile.jpg"
copyright = "2019-{{ YEAR }}"
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"

readMore = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Technology"
  weight = 200
  identifier = "tech"
  url = "/tech/"
  
  [[menu.main]]
  name = "Random Thoughts"
  weight = 300
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Whoami"
  weight = 400
  identifier = "about"
  url = "/about/"